from analisadorSintaticoSemantico.symbolsTable import SymbolsTable
from analisadorSintaticoSemantico.typesStack import TypesStack
from analisadorSintaticoSemantico.SyntaxSemanticAnalyzer import SyntaxSemanticAnalyzer