from analisadorSintaticoSemantico.symbolsTable import SymbolsTable
from analisadorSintaticoSemantico.typesStack import TypesStack
from analisadorSintaticoSemantico.SyntaxAnalyzer import SyntaxAnalyzer